openapi: 3.0.3
info:
  title: Jukboks API
  version: 0.0.1

servers:
  - url: http://localhost:8080
    description: Local API

paths:
  /ping:
    get:
      summary: Ping handler
      operationId: ping
      responses:
        '200': 
          description: "Returns OK"
  /users:
    post:
      summary: Users creation
      operationId: createUser
      responses:
        '200': 
          description: "Creates user"
        '400':
          description: "Failed in user creation: bad request"
    get:
      summary: Users showing
      operationId: showUser
      responses:
        '200': 
          description: "Users got"

            