openapi: 3.0.3
info:
    title: Jukboks API
    version: 0.0.1

servers:
    - url: http://localhost:8080
      description: Local API

paths:
    /ping:
        get:
            summary: Ping handler
            operationId: ping
            responses:
                '200':
                    description: 'Returns OK'
    /user:
        post:
            summary: User creation
            operationId: createUser
            responses:
                '201':
                    description: 'Created'
                '400':
                    description: 'Failed in user creation: bad request'
    /users:
        get:
            summary: Users showing
            operationId: showUser
            responses:
                '200':
                    description: 'Users got'
    /user/{username}:
        get:
            summary: Returns a user by username.
            parameters:
                - name: username
                  in: path
                  required: true
                  description: username of User.
                  schema:
                      type: string
                      minimum: 1
            responses:
                '200':
                    description: OK
