version: "3.8"

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./packages/jukboks-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo
      - NODE_ENV=production
    env_file: .env
    init: true

volumes:
  mongo_data: {}
